source 'https://rubygems.org'

gem 'berkshelf', '~> 3.0.0'
gem 'chef-sugar'
gem 'chefspec', '~> 3.2.0'
gem 'foodcritic', '~> 3.0.0'
gem 'kitchen-vagrant', '~> 0.14.0'
gem 'rubocop'
gem 'serverspec'
gem 'test-kitchen', '~> 1.2.0'
